virtual_modifiers:
  - CapsLock
keymap:
  - name: Emacs binding
    remap:
      CapsLock-a: home
      CapsLock-b: left
      CapsLock-c: C-c # sig int
      CapsLock-d: C-d # sig eof
      CapsLock-e: end
      CapsLock-f: right
      CapsLock-g: esc
      CapsLock-h: backspace
      CapsLock-i: C-i # C-i C-o is for vim jump back/forward
      CapsLock-j: enter
      CapsLock-k: C-k # kill to the end of line
      CapsLock-l: C-l # center view/clear console
      CapsLock-m: Shift-backslash # pipe todo
      CapsLock-Shift-m: backslash # pipe
      CapsLock-n: down
      CapsLock-o: C-o # Vim jump back
      CapsLock-p: up
      CapsLock-q: grave
      CapsLock-r: C-r # Vim undo
      CapsLock-s: C-s # TODO
      CapsLock-t: Tab
      CapsLock-Shift-u: CapsLock
      # CapsLock-u: todo
      CapsLock-v: C-v # Paste
      CapsLock-w: C-w # Firefox kill tab
      CapsLock-x: Shift-semicolon # TODO vim execute command
      Shift-CapsLock-x: semicolon #
      CapsLock-y: C-y # TODO
      CapsLock-z: C-z # TODO
      CapsLock-leftbrace: esc
      CapsLock-1: Shift-1
      CapsLock-2: Shift-2
      CapsLock-3: Shift-3
      CapsLock-4: Shift-4
      CapsLock-5: Shift-5
      CapsLock-6: Shift-6
      CapsLock-7: Shift-7
      CapsLock-8: Shift-8
      CapsLock-9: Shift-9
      CapsLock-0: Shift-0
      CapsLock-Space: LeftShift-RightShift

      CapsLock-comma: Shift-LeftBrace
      Shift-CapsLock-comma: LeftBrace
      CapsLock-dot: Shift-RightBrace
      Shift-CapsLock-dot: RightBrace

      CapsLock-semicolon: Shift-apostrophe
      Shift-CapsLock-semicolon: apostrophe

      # CapsLock-dot: #TODO
      # , comma
      # . period
      # , comma
      # . period
      # ; colon
      # ' apostrophe
      # - minus
      # = equal
      # \ backslash

    mode: default
    # TODO: does it worth it?
  - name: Navigation
    remap:
      j: down
      k: up
      h: left
      l: right
      CapsLock-g:
        set_mode: default
      CapsLock-leftbrace:
        set_mode: default
      CapsLock-k:
        set_mode: default
      Esc:
        set_mode: default
      i:
        set_mode: default
    mode: vim
modmap:
  # - remap:
  #     LeftShift:
  #       held: LeftShift
  #       alone: Space
  #       alone_timeout_millis: 200 # Optional# modmap:
  - device:
      only: ['M1Pro_X1_3AC6 Keyboard', 'Hengchangtong  HCT USB Entry Keyboard']
    remap:
      Space: CapsLock
#      Alt_L: SUPER_L
  - device:
      only: ['Logitech Wireless Keyboard']
    remap:
      b: SUPER_L
      Alt_R: SUPER_L

#   - name: Except Chrome
#     remap:
#       CapsLock: Control_L
# default_mode: default
