name:                dotfiles

dependencies:
- Clipboard
- X11
- X11
- base >= 4.7 && < 5
- containers
- directory
- filepath
- text
- xmonad
- xmonad-contrib

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields

library:
  source-dirs: src

executables:
  xmonad:
    main:                xmonad.hs
    source-dirs:
    - .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dotfiles
  xmonadctl:
    main:                xmonadctl.hs
    source-dirs:         bin
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
