
# open, rename, remove and shell
[mgr]

prepend_keymap = [
  { on = "M", run = ["plugin toggle-pane min-parent", "plugin toggle-pane min-preview"], desc = "Maximize current pane" },
  { on = "<C-o>", run = "quit", desc = "Quit" },

  # new commands from the plugin
  { on = "K", run = "plugin augment-command -- parent_arrow -1", desc = "Up parent directory" },
  { on = "J", run = "plugin augment-command -- parent_arrow 1", desc = "Down parent directory" },
  { on = [ "g", "x" ], run = "cd ~/.xmonad/", desc = "~/.xmonad" },
  { on = [ "g", "s" ], run = "cd ~/Scratch/", desc = "~/Scratch" },

  # augment existing commands
  # https://github.com/hankertrix/augment-command.yazi
  { on = "o",         run = "plugin augment-command -- open",                        desc = "Open selected files" },
  { on = "O",         run = "plugin augment-command -- open --interactive",          desc = "Open selected files interactively" },
  { on = "<Enter>",   run = "plugin augment-command -- open",                        desc = "Open selected files" },
  { on = "<S-Enter>", run = "plugin augment-command -- open --interactive",          desc = "Open selected files interactively" },
  { on = "r",         run = "plugin augment-command -- rename --cursor=before_ext",  desc = "Rename selected file(s)" },
  { on = "d",         run = "plugin augment-command -- remove",                      desc = "Trash selected files" },
  { on = "D",         run = "plugin augment-command -- remove --permanently",        desc = "Permanently delete selected files" },
  { on = "h", run = "plugin augment-command -- leave", desc = "Back to the parent directory" },
  { on = "l", run = "plugin augment-command -- enter", desc = "Enter the child directory" },
  { on = "<Left>",  run = "plugin augment-command -- leave", desc = "Back to the parent directory" },
  { on = "<Right>", run = "plugin augment-command -- enter", desc = "Enter the child directory" },
  { on = [ "c", "c" ], run = "plugin augment-command -- copy path",             desc = "Copy the file path" },
  { on = [ "c", "d" ], run = "plugin augment-command -- copy dirname",          desc = "Copy the directory path" },
  { on = [ "c", "f" ], run = "plugin augment-command -- copy filename",         desc = "Copy the filename" },
  { on = [ "c", "n" ], run = "plugin augment-command -- copy name_without_ext", desc = "Copy the filename without extension" },
  { on = "G",          run = "plugin augment-command -- arrow bot", desc = "Go to bottom" },
]
